### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by HughP** [pavpanchekha/keylogger.el#1]
Greetings,

I am interested in testing out your software for key timings. I am wondering how to install it. Not much in the read me... I'm not all that familiar with emacs I have installed it on OSX (and used it some).

**Comment by pavpanchekha** [comment]
You'll need to do two things: install my software, and have it start when Emacs starts.

To install it, download the source code somewhere and add the line

```
(load "<path-to-source>/keylogger.el")
```

to your `.emacs.d/init.el` file. Then, below that line, add the following:

```
(setf keylogger-filename "<path-to-data>/keys.el")
(keylogger-load)
(keylogger-start)
(keylogger-autosave)
```

This sets the name for the save file, loads old data, starts the keylogger, and tells it to autosave every fifteen minutes.

If you're using multiple computers, make sure to keep those save files separate! I use each computer's hostname in the file name to keep them distinct.
